env:
- TEST_SUITE='~type:feature' AFTER_SUCCESS='./travis-deploy.sh'
# Run all tests in job 2
- TEST_SUITE='~type:foo' AFTER_SUCCESS='' CC_TEST_REPORTER_ID=f0d5d763ddc6b3f980ba0fb0c38e7c27c0dffc4a5787cd7d5b8c2b0c3b2e27e2
language: ruby
rvm: 2.5
sudo: required
dist: trusty
cache:
  apt: true
  directories:
  - vendor
  - node_modules
addons:
  apt:
    packages:
    - pandoc
    - r-base
before_install:
- rvm --default use 2.5.0
- export PATH=$PATH:`yarn global bin`
- export DB=test
- export SENDER_EMAIL_ADDRESS='sender@wikiedu.org'
- nvm install stable
- nvm use stable
- node --version
- yarn --version
install:
- ruby bin/setup.rb # main setup script, will exit after installing gems
- ruby bin/setup.rb # main setup script, finishes once gems are installed
- yarn global add codeclimate-test-reporter
- gem install rubocop

before_script:
# install Code Climate test reporter
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter before-build; fi

- mkdir tmp -m 777
script:
  - yarn test && bundle exec rspec --color --profile --format documentation
    --tag $TEST_SUITE
  - rubocop --rails
after_script:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
after_success:
- "$AFTER_SUCCESS"
notifications:
  slack:
    # https://agileventures.slack.com/messages/wiki_edu-notify/
    secure: LDzHmtPo8jt9wrnH51F8PHTHl2gwOj117+bvWYgtVa4VM7SW1SL+BuiD3+DMs83VTNptek8I/kOduR0lRxIgQMqddYrQRz1O10vOcIXGLOrWbXcx0tgCQjnDcLp4BdBd3k5Ybn1pc/uf7cQXGgCUQ9lAXzAEE+V6CkrCmaCYrVE=
